create database Projeto;

CREATE TABLE Animais (
ID INTEGER PRIMARY KEY,
ESPECIE VARCHAR(40),
Nome CHAR(50),
SEXO CHAR(10),
IDADE INTEGER,
PORTE INTEGER,
CONTATO Número(4),
STATUS VARCHAR(10),
CASTRADO VARCHAR(10),
DEFICIENCIA VARCHAR(3),
LOCALIZAÇÃO VARCHAR(30),
MICROCHIP VARCHAR(30),
VACINA VARCHAR(15),
FOTO VARCHAR()
)
CREATE TABLE USUARIO_ADOTATE (
ID INTEGER PRIMARY KEY,
ID_USUARIO INTEGER,
TELEFONE INTEGER,
TERMO int
)
CREATE TABLE USUARIOS (
ID INTEGER PRIMARY KEY,
NOME VARCHAR(30),
LOCALIZAÇÃO VARCHAR(20)
)
CREATE TABLE ID (
Campo1 INTEGER PRIMARY KEY,
ID INTEGER,
DATA DATETIME,
PAGAMENTO VARCHAR(),
VALOR VARCHAR(),
FOREIGN KEY(ID) REFERENCES USUARIOS (ID)
)
CREATE TABLE DOADOR (
ID INTEGER PRIMARY KEY,
ID_USUARIO INTEGER,
TELEFONE VARCHAR(15),
Termo VARCHAR(),
ID_ANIMAL INTEGER,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS (ID),
FOREIGN KEY(ID_ANIMAL) REFERENCES Animais (ID)
)
ALTER TABLE USUARIO_ADOTATE ADD FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS (ID)