// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ONGWebAPI.Models;

#nullable disable

namespace ONGWebAPI.Migrations
{
    [DbContext(typeof(ONGContext))]
    [Migration("20220725213057_primeira_atualizacao")]
    partial class primeira_atualizacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ONGWebAPI.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Castrado")
                        .HasColumnType("bit");

                    b.Property<bool?>("Deficiencia")
                        .HasColumnType("bit");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Microchip")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Porte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioAdotanteId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioDoadorId")
                        .HasColumnType("int");

                    b.Property<string>("Vacinas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAdotanteId");

                    b.HasIndex("UsuarioDoadorId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("ONGWebAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");
                });

            modelBuilder.Entity("ONGWebAPI.Models.UsuarioAdotante", b =>
                {
                    b.HasBaseType("ONGWebAPI.Models.Usuario");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("UsuarioAdotante");
                });

            modelBuilder.Entity("ONGWebAPI.Models.UsuarioDoador", b =>
                {
                    b.HasBaseType("ONGWebAPI.Models.Usuario");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioDoador_Telefone");

                    b.HasDiscriminator().HasValue("UsuarioDoador");
                });

            modelBuilder.Entity("ONGWebAPI.Models.Animal", b =>
                {
                    b.HasOne("ONGWebAPI.Models.UsuarioAdotante", "UsuarioAdotante")
                        .WithMany("Animais")
                        .HasForeignKey("UsuarioAdotanteId");

                    b.HasOne("ONGWebAPI.Models.UsuarioDoador", "UsuarioDoador")
                        .WithMany("Animais")
                        .HasForeignKey("UsuarioDoadorId");

                    b.Navigation("UsuarioAdotante");

                    b.Navigation("UsuarioDoador");
                });

            modelBuilder.Entity("ONGWebAPI.Models.UsuarioAdotante", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("ONGWebAPI.Models.UsuarioDoador", b =>
                {
                    b.Navigation("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
