version: "3.9"
services:
  web:
    build: .
    image: webapp:latest
    environment:
      - ConnectionStrings:BancoPatinhas=Server=db;Database=ONG;User=sa;Password=123Mudar@teste
    ports:
      - "80:8080"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "123Mudar@teste"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
