namespace ONGWebAPI.Entities
{
    public enum Localizacao
    {
        Acre,
        Alagoas,
        Amapá,
        Amazonas,
        Bahia,
        Ceará,
        Distrito_Federal,
        Espirito_Santo,
        Goiás,
        Maranhão,
        Mato_Grosso,
        Mato_Grosso_do_Sul,
        Minas_Gerais,
        Para,
        Paraiba,
        Paraná,
        Pernambuco,
        Piauí,
        Rio_de_Janeiro,
        Rio_Grande_do_Norte,
        Rio_Grande_do_Sul,
        Rondônia,
        Roraima,
        Santa_Catarina,
        São_Paulo,
        Sergipe,
        Tocantis
    }
}
